### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by zodman**
by default config can comes with undefined

### CODE REVIEW

**Comment by missinglink** [comment]
related?

```bash
 Serverless Ignore Error --------------------------------------
    Cannot read property 'file' of undefined
```

**Comment by missinglink** [comment]
not sure what I'm doing wrong here but it's fixed by adding:

```
custom:
  ignore:
    file: '.slsignore'
```

**Comment by zodman** [comment]
> related?
> 
> ```shell
>  Serverless Ignore Error --------------------------------------
>     Cannot read property 'file' of undefined
> ```

yes! thats the error

**Comment by nya1** [comment]
Config issue https://github.com/nya1/serverless-ignore/issues/2 fixed, pushed 0.1.6 version

**Pull request closed without merging**
